// Generated by https://quicktype.io

export interface User {
    id:         number;
    first_name: string;
    last_name:  string;
    age:        number;
    city:       string;
    ip:         string;
    fullname:   string;
    avt:        string;
    bit:        string;
    email:      string;
}
